// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOlFPDY29Vrcrs6ZfdHbDEuU2_1bem4fU',
    appId: '1:204575361740:web:4cdee2ffe8f4abba925069',
    messagingSenderId: '204575361740',
    projectId: 'fowlpoxd',
    authDomain: 'fowlpoxd.firebaseapp.com',
    storageBucket: 'fowlpoxd.appspot.com',
    measurementId: 'G-ZK4HG2L868',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtsEYn3N0ha76oGV7FDy15bMf1QiVwswY',
    appId: '1:204575361740:android:207e06c219f231d6925069',
    messagingSenderId: '204575361740',
    projectId: 'fowlpoxd',
    storageBucket: 'fowlpoxd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDijjxc6XQxFGOJgEfFJsb5-WKzQpP8TMo',
    appId: '1:204575361740:ios:61564655e638834b925069',
    messagingSenderId: '204575361740',
    projectId: 'fowlpoxd',
    storageBucket: 'fowlpoxd.appspot.com',
    iosBundleId: 'com.example.fawlpox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDijjxc6XQxFGOJgEfFJsb5-WKzQpP8TMo',
    appId: '1:204575361740:ios:c0c600e09f0c3303925069',
    messagingSenderId: '204575361740',
    projectId: 'fowlpoxd',
    storageBucket: 'fowlpoxd.appspot.com',
    iosBundleId: 'com.example.fawlpox.RunnerTests',
  );
}
